# Generated by Django 5.1 on 2024-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_stripe_customer_id_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN_TOTAL', 'Administrador Total'), ('ADMIN_DEPARTAMENTO', 'Administrador de Departamento'), ('TECNICO_DEPARTAMENTO', 'Técnico de Departamento')], max_length=50),
        ),
    ]
